# Generated by Django 4.2.5 on 2023-09-16 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wege_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfotable',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='userinfotable',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 18, 20, 8, 23398)),
        ),
    ]
